# MongoEngine imports
import mongoengine as models

# Joker Model Mixin imports
from seocortex.joker.yahoo.mixin_models import YahooAccountMixin
from seocortex.joker.twitter.mixin_models import TwitterAccountMixin


# No _cls or _types fields (generated by MongoEngine)
class CleanDocumentMixin(object):
    meta = { 'allow_inheritance' : False }


# Embedded docs
class YahooAccountEmbedded(models.EmbeddedDocument, YahooAccountMixin, CleanDocumentMixin):
    pass

class TwitterAccountEmbedded(models.EmbeddedDocument, TwitterAccountMixin, CleanDocumentMixin):
    pass


# An embedded doc to encapsulate the others
class AccountEmbedded(models.EmbeddedDocument, CleanDocumentMixin):
    yahoo = models.EmbeddedDocumentField(YahooAccountEmbedded)
    twitter = models.EmbeddedDocumentField(TwitterAccountEmbedded)


class JokerProfile(models.Document, CleanDocumentMixin):
    accounts = models.EmbeddedDocumentField(AccountEmbedded, required = True)

    def add_account(self, account):
        if self.accounts is None:
            self.accounts = AccountEmbedded()
        if isinstance(account, YahooAccountMixin):
            self.accounts.yahoo = account
        elif isinstance(account, TwitterAccountMixin):
            self.accounts.twitter = account
        else:
            return False
        return True